library(readr)
library(tidyverse)

##  Headers <- read_csv("https://raw.githubusercontent.com/michaeljagdharry/STA9890/main/Headers.csv") ## Successfully made header tibble from Github
##  View(Headers)  OLD VERSION
Headers <- read.csv("https://raw.githubusercontent.com/michaeljagdharry/STA9890/main/Headers.csv") 

Caravan <- read_delim("https://raw.githubusercontent.com/michaeljagdharry/STA9890/main/ticdata2000.txt", 
                      "\t", escape_double = FALSE, col_names = FALSE, 
                      col_types = cols(X1 = col_factor(levels = c("1", 
                                                                  "2", "3", "4", "5", "6", "7", "8", 
                                                                  "9", "10", "11", "12", "13", "14", 
                                                                  "15", "16", "17", "18", "19", "20", 
                                                                  "21", "22", "23", "24", "25", "26", 
                                                                  "27", "28", "29", "30", "31", "32", 
                                                                  "33", "34", "35", "36", "37", "38", 
                                                                  "39", "40", "41")), 
                                       X2 = col_integer(), 
                                       X3 = col_integer(), 
                                       X4 = col_factor(levels = c("1", "2", "3", "4", "5", "6")), 
                                       X5 = col_factor(levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10")),
                                       X6 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X7 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X8 = col_factor(levels = c("0", "1", "2", "3", "4", "5")),
                                       X9 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X10 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X11 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7")),
                                       X12 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X13 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X14 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X15 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X16 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X17 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X18 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X19 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X20 = col_factor(levels = c("0", "1", "2", "3", "4", "5")),
                                       X21 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X22 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X23 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X24 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X25 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X26 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X27 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X28 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X29 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X30 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X31 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X32 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X33 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7")),
                                       X34 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X35 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X36 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X37 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X38 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X39 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X40 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X41 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X42 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X43 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8")),
                                       X44 = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6", "7", "8", "9")),
                                       X45 = col_integer(), 
                                       X46 = col_integer(),
                                       X47 = col_integer(),
                                       X48 = col_integer(),
                                       X49 = col_integer(),
                                       X50 = col_integer(),
                                       X51 = col_integer(),
                                       X52 = col_integer(),
                                       X53 = col_integer(),
                                       X54 = col_integer(),
                                       X55 = col_integer(),
                                       X56 = col_integer(),
                                       X57 = col_integer(),
                                       X58 = col_integer(),
                                       X59 = col_integer(),
                                       X60 = col_integer(),
                                       X61 = col_integer(),
                                       X62 = col_integer(),
                                       X63 = col_integer(),
                                       X64 = col_integer(),
                                       X65 = col_integer(),
                                       X66 = col_integer(),
                                       X67 = col_integer(),
                                       X68 = col_integer(),
                                       X69 = col_integer(),
                                       X70 = col_integer(),
                                       X71 = col_integer(),
                                       X72 = col_integer(),
                                       X73 = col_integer(),
                                       X74 = col_integer(),
                                       X75 = col_integer(),
                                       X76 = col_integer(),
                                       X77 = col_integer(),
                                       X78 = col_integer(),
                                       X79 = col_integer(),
                                       X80 = col_integer(),
                                       X81 = col_integer(),
                                       X82 = col_integer(),
                                       X83 = col_integer(),
                                       X84 = col_integer(),
                                       X85 = col_integer(),
                                       X86 = col_factor(levels=c("0", "1"))), trim_ws = TRUE) ## It worked after many attempts, Pull of tibble data

colnames(Caravan) = Headers
Headers2 <- t(colnames(Headers))
colnames(Caravan) = Headers2
View(Caravan)
str(Caravan)
